### ISSUE TITLE
xunsearch1.4.13清空索引报错

### ISSUE THREAD

**Issue by xswolf** [hightman/xunsearch#72]
执行命令：/usr/local/xunsearch/sdk/php/util/Indexer.php --clean demo

报错如下：
[XSException] xunsearch/sdk/php/lib/XS.php(2447): Failed to create home directoy of the project(S#508)
#0 xunsearch/sdk/php/lib/XS.php(1104): XSServer->execCommand(Array, 201, 128)
#1 xunsearch/sdk/php/lib/XS.php(2421): XSIndex->execCommand(Array, 201)
#2 xunsearch/sdk/php/lib/XS.php(2374): XSServer->setProject('demo')
#3 xunsearch/sdk/php/lib/XS.php(2356): XSServer->open('8383')
#4 xunsearch/sdk/php/lib/XS.php(371): XSServer->__construct('8383', Object(XS))
#5 xunsearch/sdk/php/lib/XS.php(263): XS->getIndex()
#6 Indexer.php(157): XSComponent->__get('index')
#7 {main}

望指点

**Comment by coolzbw** [comment]
同问
